apiVersion: apps/v1
kind: Deployment
metadata:
  name: travelbot-deployment
  labels:
    app: travelbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travelbot
  template:
    metadata:
      labels:
        app: travelbot
    spec:
      containers:
      - name: travelbot
        image: lodacr.azurecr.io/travelbot:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: travelbot-service
spec:
  type: LoadBalancer
  selector:
    app: travelbot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  