apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatrag-deployment
  labels:
    app: chatrag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatrag
  template:
    metadata:
      labels:
        app: chatrag
    spec:
      containers:
      - name: chatrag
        image: lodacr.azurecr.io/chatrag:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: chatrag-service
spec:
  type: LoadBalancer
  selector:
    app: chatrag
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  